# Generated by Django 5.1.7 on 2025-03-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='segundoAp',
            new_name='SegundoAp',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
    ]
